package com.example.demo.model.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.hibernate.annotations.CreationTimestamp;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity name : HabitLog
 * Table name  : habit_log
 * +----+---------+----------+------+--------------+---------------+---------------+-----------------+---------------------+
 * | id | user_id | habit_id | note | reward_coins | penalty_coins | auto_generated |   created_at    |
 * +----+---------+----------+------+--------------+---------------+---------------+-----------------+---------------------+
 * |  1 |    1    |     3    | ...  |     10.00    |      0.00     |       0       | 2025-06-12 09:00|
 * +----+---------+----------+------+--------------+---------------+---------------+-----------------+---------------------+
 *
 * 欄位說明
 * ───────────────────────────────────────────────────────────────────────────────
 * id              BIGINT          PK AUTO_INCREMENT        打卡紀錄 ID
 * user_id         BIGINT          NOT NULL, FK → users(id) 打卡使用者 ID
 * habit_id        BIGINT          NOT NULL, FK → habit(id) 所屬習慣 ID
 * note            TEXT            NULL                     心情筆記
 * reward_coins    DECIMAL(12,2)   DEFAULT 0                實際獲得金幣
 * penalty_coins   DECIMAL(12,2)   DEFAULT 0                如果未完成，扣除金幣
 * auto_generated  TINYINT(1)      DEFAULT 0                是否系統自動補記錄
 * created_at      DATETIME        DEFAULT CURRENT_TIMESTAMP 建立時間（打卡時間）
 * ───────────────────────────────────────────────────────────────────────────────
 */


@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "habit_log")
public class HabitLog {

    // ────────────────────────────────────────────────────────────────
    // 主鍵：BIGINT  PK AUTO_INCREMENT
    // ────────────────────────────────────────────────────────────────
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    // 打卡使用者 ID: BIGINT  NOT NULL  (FK → users.id)
    @Column(name = "user_id", nullable = false)
    private Long userId;

    // 對應習慣 ID: BIGINT  NOT NULL  (FK → habit.id)
    @Column(name = "habit_id", nullable = false)
    private Long habitId;

    // 心情筆記: TEXT  NULL
    @Column(name = "note", columnDefinition = "TEXT")
    private String note;

    // 實際獲得金幣: DECIMAL(12,2)  DEFAULT 0
    @Column(name = "reward_coins", precision = 12, scale = 2, columnDefinition = "DECIMAL(12,2) DEFAULT 0")
    private BigDecimal rewardCoins = BigDecimal.ZERO;

    // 若未完成打卡之扣金幣: DECIMAL(12,2)  DEFAULT 0
    @Column(name = "penalty_coins", precision = 12, scale = 2, columnDefinition = "DECIMAL(12,2) DEFAULT 0")
    private BigDecimal penaltyCoins = BigDecimal.ZERO;

    // 是否系統自動補上未打卡記錄TINYINT(1):  DEFAULT 0
    @Column(name = "auto_generated", columnDefinition = "TINYINT(1) DEFAULT 0", nullable = false)
    private Boolean autoGenerated = false;

    // 建立時間（打卡時間）: DATETIME  DEFAULT CURRENT_TIMESTAMP
    @CreationTimestamp
    @Column(name = "created_at", updatable = false, nullable = false)
    private LocalDateTime createdAt;
}
